# -*- coding: utf-8 -*-
"""Basics of Python WEEK - 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mVOgImvsq3IOXCnTG_TmimvyDsmoIxv0
"""

var1 = 10
var2 = 12
var3 = var1 + var2
print(var3)

type(var3)

var1 = 10
var2 = 12.2
var3 = var1 + var2
print(var3)

type(var3)

3+6

(50 - 5*6) / 4

17 / 3

17 // 3

17 % 3

'sam\'s eggs'

s = 'First line.\tSecond line.'

s

print(s)

print( 'First line.\nSecond line.')

5*'un' + 'ited'

a = 'Py'       'thon'
print(a)

word = 'Python'

print(word)

print(word[0])

print(word[5])

word[-1]

word[-6]

word

word[2:4]

word[ :4]

word[ 2: ]

word[ :4] + word[4: ]

word[0:6 : 2]

word[ : : -1]

word[20:21]

word[:]

word[40:]

'J'+word[1:]

len(word)

len('Anaconda')