# -*- coding: utf-8 -*-
"""Python Basic Assignment  1 - 2420030692.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AKcj3HkBTDjSMf5IIeMWdRtGxZB4pkcM

Variables & Data Types
"""

#1
name = input("Enter your name")
age = int(input("Enter your age"))
favnum = float(input("Enter your fav number"))

print(f"Welcome,{name}!")

diff = 100 - age
year = diff + 2025
print(f"You will turn 100 years old in the year: {year}")

doubled = favnum * 2
print(f"Your fav number doubled is: {doubled}")

"""Conditional Statements

"""

#2
n = int(input("Enter a number"))

if(n % 2 == 0):
  print("The number is even")
else:
    print("The number is odd")

if(n>0):
  print("Number is positive")
elif(n<0):
  print("Number is negative")
else:
  print("Number is 0")

"""Loops

"""

#3
#using for loop

for i in range(2,51,2):
  print(i,end=" ")

#3
#using while loop

i = 2
while i <= 50:
    print(i, end=" ")
    i += 2

"""Lists and Dictionaries

"""

#1
foods = []
print("Enter five of your favorite foods:")

for i in range(5):
    food = input(f"Food {i+1}: ")
    foods.append(food)

print("Your favorite foods list:", foods)
food_dict = {food: len(food) for food in foods}
print("Dictionary of food items and their lengths:", food_dict)

"""Functions

"""

import math

def calculate_area(shape, dimension1, dimension2=None):
    if shape == "circle":
        return math.pi * (dimension1 ** 2)

    elif shape == "rectangle":
        return dimension1 * dimension2

    elif shape == "triangle":
        return 0.5 * dimension1 * dimension2

    else:
        return "Invalid shape! Please choose circle, rectangle, or triangle."

print("Circle (radius = 5):", calculate_area("circle", 5))
print("Rectangle (length = 4, width = 7):", calculate_area("rectangle", 4, 7))
print("Triangle (base = 6, height = 8):", calculate_area("triangle", 6, 8))

"""String Manipulation"""

sentence = input("Enter a sentence: ")
vowels = "aeiouAEIOU"
vowel_count = sum(1 for ch in sentence if ch in vowels)
print("Number of vowels in the sentence:", vowel_count)
reversed_sentence = sentence[::-1]
print("Reversed sentence:", reversed_sentence)
uppercase_sentence = sentence.upper()
print("Uppercase sentence:", uppercase_sentence)

"""File Handling

"""

with open("data.txt", "w") as file:
    file.write("Hello, Python!\n")
    file.write("Learning file handling.\n")
    file.write("Python is fun!\n")

with open("data.txt", "r") as file:
    content = file.read()
    print("File content:\n")
    print(content)

"""Error Handling


"""

try:

    num1 = float(input("Enter the first number: "))
    num2 = float(input("Enter the second number: "))

    result = num1 / num2
    print("Result of division:", result)

except ZeroDivisionError:
    print("Error: Cannot divide by zero!")

except ValueError:
    print("Error: Invalid input! Please enter numeric values only.")